[Switch]
DEVICE = "template"
DEVICE_SERIAL_NUM = ""
SWITCH_DEVICE_ID = ""
SWITCH_LOCATION = "Unknown"

SWITCH_ENABLE_PIN = 5
SWITCH_ACTIVE_LEVEL = "high"
# or "low"

SWITCH_1_LABEL = "Fan"
SWITCH_1_CHANNEL_ID = "S1-"
SWITCH_1_PIN = 26
SWITCH_1_LAST_STATE = false
SWITCH_1_OVERRIDE_SCRIPT = false

SWITCH_2_LABEL = "Light"
SWITCH_2_CHANNEL_ID = "S2-"
SWITCH_2_PIN = 20
SWITCH_2_LAST_STATE = false
SWITCH_2_OVERRIDE_SCRIPT = false

SWITCH_3_LABEL = "Pump"
SWITCH_3_CHANNEL_ID = "S3-"
SWITCH_3_PIN = 21
SWITCH_3_LAST_STATE = false
SWITCH_3_OVERRIDE_SCRIPT = false
